# Generated by Django 3.1.1 on 2020-09-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionário',
            new_name='Funcionario',
        ),
    ]
